server.port=8080

# Conexión a tu base de datos local
spring.datasource.url=jdbc:mysql://localhost:3306/falta_uno?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=abc123.

# Sincronización automática de entidades JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true